### ISSUE TITLE
Integrate in the Prism repo?

### ISSUE THREAD

**Issue by weitzhandler** [nventive/Uno.Prism#5]
Hi,

Any plans to integrate Uno.Prism with the main [Prism Library repo](/PrismLibrary/Prism)?

**Comment by weitzhandler** [comment]
I'd say this is the number one issue I have with Uno.

**Comment by weitzhandler** [comment]
@jeromelaban Is Uno.Prism ever gonna merge within Prism?

**Comment by jeromelaban** [comment]
Eventually. We still need to have the support for the proper WebAssembly targetframeworks to integrate with original repositories (Prism is not the only one).

**Comment by weitzhandler** [comment]
I see.
This is amazing, thank you!

**Comment by weitzhandler** [comment]
@jeromelaban 

So what libraries will I bump into problems with, when working with Uno? Wouldn't any .NET Standard library work with Uno?

Regarding Prism, would it be feasible to include a Prism template in the [Uno Platform Solution Templates](https://marketplace.visualstudio.com/items?itemName=nventivecorp.uno-platform-addin) extension?

Thanks for everything!

**Comment by jeromelaban** [comment]
@weitzhandler any netstandard 2.0 library will build and mostly work with mono/Xamarin (and by extension Uno). The support for features the library is used is bound to what the underlying runtime supports.

For Prism, yes it is possible (https://github.com/nventive/Uno/issues/443) we have not started working on that yet. But if you have a simple solution already setup, it's quite easy to add it to the vsix layout.

**Comment by weitzhandler** [comment]
How about just adding to HelloWorld from the Prism example to the vsix, so it's easier to get started from a template rather than copy-pasting code from the OS solution?

**Comment by jeromelaban** [comment]
@weitzhandler Sure, it can be used as well, we haven't done that yet. If you have done it already, it can make the issue more forward faster.
